# Generated by Django 4.0.1 on 2022-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('paragraph', models.CharField(max_length=256)),
                ('observation', models.CharField(max_length=128)),
                ('image_link', models.CharField(max_length=512)),
                ('reference_link', models.CharField(max_length=512)),
            ],
        ),
    ]
